# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dldCyAkaGk-3T1Rp2cm7mf9tqmMeFZZd
"""

import openai

def qa_function(user_input):
    # 使用 GPT-3 模型来生成回答
    response = openai.Completion.create(
        model="text-davinci-003",
        prompt=user_input,
        temperature=0.7,
        max_tokens=50
    )

    # 提取生成的回答文本
    answer = response.choices[0].text.strip()

    return answer